apiVersion: batch/v1
kind: CronJob
metadata:
  name: certbot
spec:
  schedule: "0 0 */30 * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: certbot
        spec:
          containers:
          - name: certbot
            image: eilerb101/certmgr:latest
            env:
            - name: KUBECONFIG
              value: "/root/.kube/config"
            - name: clusterfqdn
              valueFrom:
                configMapKeyRef:
                  name: cert-vars
                  key: clusterfqdn
            - name: admin_email
              valueFrom:
                configMapKeyRef:
                  name: cert-vars
                  key: admin_email
            volumeMounts:
            - name: kubeconfig-volume
              mountPath: "/root/.kube/config"
              subPath: config
          volumes:
          - name: kubeconfig-volume
            secret:
              secretName: kcon
          restartPolicy: OnFailure
