apiVersion: v1
kind: ConfigMap
metadata:
  name: edns-vars
data:
  #TTL for your DNS records
  ttl: "30"
  #Base URL From your Akamai eDNS config
  baseurl: "https://akab-bufit2kj3dzhh2q4-lec3w6tjcgu6grbn.luna.akamaiapis.net"
  record_type: "A"
  #Leave this blank unless you are using the accountSwitchKey
  append: "?accountSwitchKey=B-M-1YX7F48"
  #Give your database a name
  dbname: comcast
  ###Don't change sqlns unless you deploy mysql outside of the default namespace
  sqlns: default
  ##This is the record that can be updated by the test ddns user and is only created at first start of mysql
  test_hostname: demo.afcasul.com
  #########The next 2 vars are for the cert management
  clusterfqdn: "comcast.linode.eiler.rocks"
  admin_email: "beiler@amakai.com"
 
